name: Visitor Count Smoke Test

on:
  push:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./backend
          spec: cypress/e2e/*.cy.js
