version = 0.1

[default.global.parameters]
stack_name = "aws-sam-cli-managed-default"
region = ""

[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = false
s3_bucket = ""
s3_prefix = "sam-artifacts"
parameter_overrides = [
  "DbUrl=placeholder-db-url",
  "S3BucketName=placeholder-bucket-name"
]
